services:
  scarletpanda:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3020:3000
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scarletpanda.rule=Host(`panda.crow.ovh`)"

networks:
  traefik_proxy:
    external: true